"""unique rows

Revision ID: ab16409eeb29
Revises: 3b92ec100c4c
Create Date: 2024-11-29 21:48:09.461844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab16409eeb29'
down_revision: Union[str, None] = '3b92ec100c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cargo_type_datetime', 'cargo', ['cargo_type', 'datetime'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cargo_type_datetime', table_name='cargo')
    # ### end Alembic commands ###
