"""cargo time

Revision ID: f83633b416e2
Revises: 836957a0872d
Create Date: 2024-11-29 19:44:01.836746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83633b416e2'
down_revision: Union[str, None] = '836957a0872d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo', sa.Column('datetime', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo', 'datetime')
    # ### end Alembic commands ###
